version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: notes-app-db
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_password
      POSTGRES_DB: notes_db
    ports:
      - "5499:5432"
    volumes:
      - notes_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notes_user -d notes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  notes_data:
    name: notes_app_data
